# Generated by Django 2.1.7 on 2019-04-24 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carreras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nControl', models.CharField(max_length=8, unique=True, verbose_name='Numero de Control')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre(s) del Alumno')),
                ('ap_Pat', models.CharField(max_length=25, verbose_name='Apellido Paterno')),
                ('ap_Mat', models.CharField(max_length=25, verbose_name='Apellido Materno')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30, verbose_name='Password')),
                ('fechaIngreso', models.DateField()),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carreras.Carrera')),
                ('especialidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carreras.Especialidad')),
            ],
        ),
    ]
