# Generated by Django 2.1.7 on 2019-04-24 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.CharField(max_length=50, unique=True, verbose_name='Nombre de Carrera')),
                ('clave', models.CharField(max_length=8, unique=True, verbose_name='Clave de Carrera')),
                ('color', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=50, unique=True, verbose_name='Nombre de la Especialidad')),
                ('clave', models.CharField(max_length=8, unique=True, verbose_name='Calve de la Especialidad')),
                ('color', models.CharField(max_length=15)),
                ('planEstudios', models.CharField(max_length=15, verbose_name='Plan de Estudios')),
            ],
        ),
    ]
