# Generated by Django 2.1.7 on 2019-04-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.CharField(max_length=50, unique=True)),
                ('clave', models.CharField(max_length=8, unique=True)),
                ('color', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=50, unique=True)),
                ('clave', models.CharField(max_length=8, unique=True)),
                ('color', models.CharField(max_length=15)),
                ('planEstudios', models.CharField(max_length=15)),
            ],
        ),
    ]
